name: Sync upstream

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨 3 点自动同步
  workflow_dispatch:     # 手动触发支持

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "yourgithub"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/LibreSpark/LibreTV.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync from upstream"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
